language: objective-c
before_install:
  - gem install xcpretty
  - gem install cocoapods -v '0.33.1'
before_script:
  - export LANG=en_US.UTF-8
script:
  - set -o pipefail
  - xcodebuild -workspace ReactiveNetworking.xcworkspace -scheme 'ReactiveNetworking iOS' -sdk iphonesimulator -configuration Debug test | xcpretty -c && xcodebuild -workspace ReactiveNetworking.xcworkspace -scheme 'ReactiveNetworking Mac' -sdk macosx -configuration Debug test | xcpretty -c
